// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiGHXxdZmxp_XgcZhGK6H4dqtzpzFIXYk',
    appId: '1:199120866837:web:7156ccaeafa706e0e4481c',
    messagingSenderId: '199120866837',
    projectId: 'attendance-app-729e7',
    authDomain: 'attendance-app-729e7.firebaseapp.com',
    storageBucket: 'attendance-app-729e7.appspot.com',
    measurementId: 'G-MN5K0H92P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzG0nBe1DK1A2_2EBlhJCbq2wce5XuQAI',
    appId: '1:199120866837:android:54b5998192e0b371e4481c',
    messagingSenderId: '199120866837',
    projectId: 'attendance-app-729e7',
    storageBucket: 'attendance-app-729e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR1K5DqMoh-SBcpAbnGnJQ0RlyX93oYwc',
    appId: '1:199120866837:ios:ca9a9c7f01ae9715e4481c',
    messagingSenderId: '199120866837',
    projectId: 'attendance-app-729e7',
    storageBucket: 'attendance-app-729e7.appspot.com',
    iosClientId: '199120866837-9v7u91mc3jpum5s4dg757q5imsrio1gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ftest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR1K5DqMoh-SBcpAbnGnJQ0RlyX93oYwc',
    appId: '1:199120866837:ios:ca9a9c7f01ae9715e4481c',
    messagingSenderId: '199120866837',
    projectId: 'attendance-app-729e7',
    storageBucket: 'attendance-app-729e7.appspot.com',
    iosClientId: '199120866837-9v7u91mc3jpum5s4dg757q5imsrio1gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ftest',
  );
}
